//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR_Project_4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_QR_1Entities2 : DbContext
    {
        public DB_QR_1Entities2()
            : base("name=DB_QR_1Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Estado_QR> Estado_QR { get; set; }
        public virtual DbSet<Estado_Transaccion> Estado_Transaccion { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<QR> QR { get; set; }
        public virtual DbSet<Rel_Transaccion_Producto> Rel_Transaccion_Producto { get; set; }
        public virtual DbSet<Respuesta_QR> Respuesta_QR { get; set; }
        public virtual DbSet<Tipo_Producto> Tipo_Producto { get; set; }
        public virtual DbSet<Tipo_QR> Tipo_QR { get; set; }
        public virtual DbSet<Transaccion> Transaccion { get; set; }
    }
}
