//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR_Project_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QR()
        {
            this.Respuesta_QR = new HashSet<Respuesta_QR>();
        }
    
        public int ID_QR { get; set; }
        public Nullable<int> ID_Cliente { get; set; }
        public Nullable<int> ID_Departamento { get; set; }
        public Nullable<int> ID_Tipo_QR { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public Nullable<int> ID_Estado_QR { get; set; }
        public string Comentario { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Estado_QR Estado_QR { get; set; }
        public virtual Tipo_QR Tipo_QR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuesta_QR> Respuesta_QR { get; set; }
    }
}
