//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR_Project_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta_QR
    {
        public int ID_Respuesta_QR { get; set; }
        public Nullable<int> ID_QR { get; set; }
        public Nullable<int> ID_Empleado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Detalle { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual QR QR { get; set; }
    }
}
